language:
    - python
cache:
    - pip
python:
    - "3.7"
install:
    - "pip install --upgrade -r requirements.txt"
script:
    - bash travis_ci/run_tests.sh 'pylint'
    - bash travis_ci/run_tests.sh 'pyflakes'
    - bash travis_ci/run_tests.sh 'mypy'
    - bash travis_ci/run_tests.sh 'pytest'
after_success:
    - coveralls

matrix:
    include:
        - os: linux
          dist: xenial
          sudo: true
